/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fc',
        'surface-container': '#ecedf6',
        'surface-container-high': '#e6e8f0',
        'surface-container-highest': '#e1e2ea',
        'surface-dim': '#d8dae2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#e1e2ea',
        'on-surface': '#191c22',
        'on-surface-variant': '#414752',
        'inverse-surface': '#2e3037',
        'inverse-on-surface': '#eff0f9',
        outline: '#727784',
        'outline-variant': '#c1c6d4',
        'surface-tint': '#005db7',
        primary: '#005db7',
        'on-primary': '#ffffff',
        'primary-container': '#5b9dff',
        'on-primary-container': '#00346a',
        'inverse-primary': '#a9c7ff',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#a9c7ff',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#00468c',
        secondary: '#585f6c',
        'on-secondary': '#ffffff',
        'secondary-container': '#dce2f3',
        'on-secondary-container': '#5e6572',
        'secondary-fixed': '#dce2f3',
        'secondary-fixed-dim': '#c0c7d6',
        'on-secondary-fixed': '#151c27',
        'on-secondary-fixed-variant': '#404754',
        tertiary: '#845400',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d88d00',
        'on-tertiary-container': '#4b2e00',
        'tertiary-fixed': '#ffddb5',
        'tertiary-fixed-dim': '#ffb958',
        'on-tertiary-fixed': '#2a1800',
        'on-tertiary-fixed-variant': '#643f00',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-background': '#191c22',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        gutter: '20px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(5px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
